<a href="https://colab.research.google.com/github/ademaratioluwatoyin/Playing-with-tensorflow/blob/main/PlayWithTensorflow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf

a = tf.constant([1,2,3])
b = tf.constant([5,6,7])
c = tf.add(a,b)
print(c)

tf.Tensor([ 6  8 10], shape=(3,), dtype=int32)


In [ ]:
a = tf.constant('Hello, World!')
print(a)

tf.Tensor(b'Hello, World!', shape=(), dtype=string)


In [ ]:
tf.print(a)

Hello, World!


In [ ]:
tf.print(c)

[6 8 10]


In [ ]:
c

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([ 6,  8, 10], dtype=int32)>

In [ ]:
a

<tf.Tensor: shape=(), dtype=string, numpy=b'Hello, World!'>

In [ ]:
import tensorflow as tf
from tensorflow import math

In [ ]:
a = 54
b = 60
c = math.add(a,b)
tf.print(c)

114


In [ ]:
a = [54, 60, 100]
sum = 0
for i in a:
  sum = math.add(sum, i)
  
tf.print(sum)


214


In [ ]:
def fizzbuzz(max_num):
  counter = tf.constant(0)
  max_num = tf.convert_to_tensor(max_num)
  for num in range(1, max_num.numpy()+1):
    num = tf.constant(num)
    if int(num % 3) == 0 and int(num % 5) == 0:
      print('FizzBuzz')
    elif int(num % 3) == 0:
      print('Fizz')
    elif int(num % 5) == 0:
      print('Buzz')
    else:
      print(num.numpy())
    counter += 1

In [ ]:
fizzbuzz(15)

1
2
Fizz
4
Buzz
Fizz
7
8
Fizz
Buzz
11
Fizz
13
14
FizzBuzz


In [ ]:
c = tf.constant([[4.0, 5.0], [10.0, 1.0]])

# Find the largest value
print(tf.reduce_max(c))
# Find the index of the largest value
print(tf.argmax(c))
# Compute the softmax
print(tf.nn.softmax(c))

tf.Tensor(10.0, shape=(), dtype=float32)
tf.Tensor([1 0], shape=(2,), dtype=int64)
tf.Tensor(
[[2.6894143e-01 7.3105860e-01]
 [9.9987662e-01 1.2339458e-04]], shape=(2, 2), dtype=float32)


In [ ]:
tf.print(c)

[[4 5]
 [10 1]]


In [ ]:
c

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[ 4.,  5.],
       [10.,  1.]], dtype=float32)>

In [ ]:
c.shape

TensorShape([2, 2])

In [ ]:
c.ndim

2

In [ ]:
c.dtype

tf.float32

In [ ]:
print(c[1].numpy())

[10.  1.]
